apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-service
spec:
  selector:
    app: uptime-kuma
    type: ClusterIP # LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001 
      # nodePort: 30001 
